### ISSUE TITLE
`juvix init` generated `juvix.yaml` is incompatible with the `internal-build-dir`

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2274]
A juvix project created using `juvix init` comes with a pre-populated dependencies field that points to the stdlib dependency in the default build directory `.juvix-build`:

juvix.yaml
```yaml
dependencies:
- .juvix-build/stdlib/
name: foo
version: 0.0.0
```

However we allow users of `juvix compile` to override the build directory using the `--internal-build-dir` flag. This currently works because (see https://github.com/anoma/juvix/issues/2273) the default stdlib is always copied to `.juvix-build/stdlib`, the `--internal-build-dir`.

To fix this we could implement:

* https://github.com/anoma/juvix/issues/1994

and then have some way of referencing the global project dir in a dependency (perhaps with a magic `#GLOBAL_PROJECT` variable?, though this is ugly, but the global project location is dynamic, it depends on `XDG_CONFIG_HOME`).

```
dependencies:
- #GLOBAL_PROJECT/<current_juvix_version_at_juvix_init_invokcation_time>/stdlib
```

**Comment by paulcadman** [comment]
Discussed with the team.

We should use an external dependency for the standard library:

```
dependencies:
- git:
     url: https://github.com/anoma/juvix-stdlib
     name: stdlib
     ref: v1.2.3  
```

We should publish releases of the standard library before doing this:

* https://github.com/anoma/juvix-stdlib/issues/83
