### ISSUE TITLE
`juvix init` adds `file` field in generated juvix.yaml

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2380]
To reproduce run `juvix init` with default answers.

The resulting juvix yaml looks like:

```yaml
dependencies:
- .juvix-build/stdlib/
file: []
name: myName
version: 0.0.0
```

The `file` field is present, but it is not part of the package spec.
