### ISSUE TITLE
Automatically update the lock file when the project dependencies and lock file are not in sync

### ISSUE THREAD

**Issue by paulcadman** [anoma/juvix#2464]
Say you have the following project:

```yaml
name: abc
dependencies:
- .juvix-build/stdlib
- git:
    name: test
    url: https://github.com/anoma/juvix-test
    ref: v0.6.0
```

After compiling the project the following juvix.lock.yaml is generated:

```yaml
# This file was autogenerated by Juvix version 0.5.2.
# Do not edit this file manually.

dependencies:
- path: .juvix-build/stdlib
  dependencies: []
- git:
    name: test
    ref: a94c61749678ff57556ee6e4cb1f8fbbddbc4ab1
    url: https://github.com/anoma/juvix-test
  dependencies:
  - git:
      name: stdlib
      ref: 4facf14d9b2d06b81ce1be1882aa9050f768cb45
      url: https://github.com/anoma/juvix-stdlib
    dependencies: []
```

The `v0.6.0` tag has been dereferenced to the git hash of the corresponding commit. If you now update the project file to point to a new version of `juvix-test` and rebuild the project, the `v0.6.0` code is still used because the lock file has not changed.

The proposal in this issue is to detect when the project file dependencies and the lock file are not in sync and regenerate the lock file using the new information.
